
# Site settings
title: Zhiruo's Cat World
email: zhaozhiruo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Zhao Zhiruo
email: zhaozhiruo@gmail.com 
facebook_username: zhaozhiruo
twitter_username:
github_username: zhaozhiruo
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright:

# API settings
google_api_key: AIzaSyDrsY7aIMwxUOqRD0q0AzhhPm4EpSRid0k

# Build settings
gems: [jekyll-paginate]

markdown: kramdown
# toc_levels: 1..2

